### PR TITLE
BUGFIX: Replace relative file paths in included css

### PR DESCRIPTION
**Pull request by dlubitz**
with absolute ones.

NEOS-1502 #close

### CODE REVIEW

**Comment by aertmann** [comment]
hey I guess this should be pushed to a lower branch? also can you tell what it fixes exactly? where is there broken references to a file in the setup?

**Comment by dlubitz** [comment]
@aertmann Which is the lowest supported branch?
That fixes the loading of the fonts: https://github.com/neos/setup/blob/master/Resources/Public/Styles/Setup.css#L9-L27

**Comment by aertmann** [comment]
that would be `2.0`

**Comment by aertmann** [comment]
gotcha, you mean the error message view.. can confirm..

thanks for fixing, please open against `2.0` and we upmerge it..

**Comment by dlubitz** [comment]
Replaced by https://github.com/neos/setup/pull/9 against 2.0

**Pull request closed without merging**
