### PR TITLE
BUGFIX: Prevent Fatal Error in Setup

### PR DESCRIPTION
**Pull request by bwaidelich**
This is a hotfix for a regression introduced with https://github.com/neos/flow-development-collection/pull/499.

Background:
The latest `Http\RequestHandler` of Flow internally uses
the `ComponentChain` to determine the current `Request`/`Response`.

This package uses a specialized handler which doesn't rely on
the `ComponentChain` leading to a Fatal Error.

### CODE REVIEW

**Comment by aertmann** [comment]
needs to go into the 2.0 branch right?

**Comment by bwaidelich** [comment]
> needs to go into the 2.0 branch right?

I'm not  sure, 2.0 is used in Neos 2.0+ and the fix is only required for Neos 2.3.x. I guess we should probably create a 2.3 branch in the setup and apply it there!?

**Comment by albe** [comment]
The evils of inheritance... Makes sense, but be aware that the $request and $response properties will also be removed with 4.0 - so maybe already copy them over

**Comment by bwaidelich** [comment]
> be aware that the $request and $response properties will also be removed with 4.0

That's news to me. Is that documented somewhere or is there a PR for this?

Anyways, I rather merge this now to fix the fatal.
I'd suggest to merge it into `master` and then create a branch `2.3` and require that in the affected distributions. Does that make sense?

**Comment by albe** [comment]
> Is that documented somewhere or is there a PR for this?

https://github.com/neos/flow-development-collection/pull/500

**Comment by aertmann** [comment]
@bwaidelich: I'd rather avoid a separate version if it can be done in backwards compatible way, which this seems to be..

**Comment by bwaidelich** [comment]
I messed up the rebase, see #28

**Pull request closed without merging**
